### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by grv87** [toy/image_optim_pack#13]
Do you have any plans to support Windows as well?

**Comment by toy** [comment]
Few times there were ideas, but for now no plans; while I would like this gem to make it very simple to use `image_optim` on every platform were ruby can run, I think there is way more complexity involved in adding windows support than it was in adding *bsd support or may be in adding ARM support (for raspberry; while not a different os, but still not supported by virtualbox).

**Comment by grv87** [comment]
@toy, is there a list of tasks that should be performed to add support for new platform?

**Comment by toy** [comment]
Currently the binaries building process requires a platform that can be run on virtualbox through vagrant, has a package manager, allows connection using ssh and running POSIX compilant shell scripts, gnu make, c compiler and several other tools. Probably this is all somehow possible on windows, but my knowledge about the platform is very vague. Maybe there is a different, easier way for windows, like for example for ARM on raspberry it may be easier to ssh to a real device. Anyway you can at least check what I did for bsd systems in dfda0f82387fb1f9f9d8e1e68bfba6dca3fd280a.
In the end it should be made possible to compile all platform binaries in fully automated way in decent amount of time and the binaries should be as self contained as possible (in balance with their size).

**Comment by toy** [comment]
Please reopen or open a new issue if you decide to undertake the task
