### ISSUE TITLE
pngout and svgo not found (with default options)

### ISSUE THREAD

**Issue by jmuheim** [toy/image_optim_pack#19]
I use `image_optim` as follows:

```rb
      image_optim = ImageOptim.new allow_lossy: true
      image_optim.optimize_images!(Dir["#{File.dirname(file.file)}/*.png"])
```

This results in messages in the console:

```
pngout worker: `pngout` not found; please provide proper binary or disable this worker (--no-pngout argument or `:pngout => false` through options)
svgo worker: `svgo` not found; please provide proper binary or disable this worker (--no-svgo argument or `:svgo => false` through options)
```

When using 

```rb
      image_optim = ImageOptim.new allow_lossy: true,
                                   pngout: false,
                                   svgo: false
```

it works without errors.

**Comment by toy** [comment]
That is expected unless you manually installed `pngout` and `svgo` to some directory in `PATH` environment variable. `pngout` license doesn't allow bundling and `svgo` is a bit trickier to bundle, so wasn't yet done. Those are just warnings if you use `image_optim_pack` (which you apparently do use).

**Comment by jmuheim** [comment]
Exactly, I use image_optim_pack. So if this is expected behaviour, I'm alright with it. Thank you.
