### ISSUE TITLE
Can't find binaries after installation

### ISSUE THREAD

**Issue by alexbel** [toy/image_optim_pack#2]
Hey Ivan,

Maybe I'm doing something wrong, but after `bundle install` I can't see any of those libraries.
It doesn't put any libs into `bin` folder. I also tried to run `bundle install --binstubs` but no success. It generates a bunch bins for other gems, but no libs from this gem.
Gemfile does include:
```
gem 'image_optim', '~> 0.20.2'
gem 'image_optim_pack'
```

**Comment by toy** [comment]
`image_optim_pack` provides binaries only for `image_optim` gem. It finds directory from `vendor/*/*` with binaries which work on current system and adds that directory to paths used by `image_optim`. Binaries are not made available globally not to mess with binaries available in `PATH` (as binaries from gems are normally available there). If you want to make them available in the environment of your app you can do something like this:
```
system 'jpeg-recompress -V' # fails if jpeg-recompress is not available in PATH

require 'image_optim_pack' # or 'image_optim/pack'
ENV['PATH'] += ":#{ImageOptim::Pack.path}"

system 'jpeg-recompress -V'
```

**Comment by alexbel** [comment]
Oh, I see.
Thanks for the great explanation.
